# -*- coding: utf-8 -*-
"""Programas_metro_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj0NjFgv0Gt6gYayE_1k2ZLtuLFT0LjW
"""

from google.colab import drive
drive.mount('/content/drive')

'''linea mas afluente'''
import matplotlib.pyplot as plt
import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      lineas_m.append(renglon[3])
      afluencia.append(renglon[5])
      lineas += 1
lin=[]
for i in range (len(lineas_m)):
  if lineas_m[i] not in lin:
    lin.append(lineas_m[i])
sumas=[]
for j in range(len(lin)):
  suma=0
  for k in range(len(lineas_m)):
    if lineas_m[k] == lin[j]:
      suma=suma+int(afluencia[k])
  sumas.append(suma)
max= sumas[0]
pos= 1
for t in range(len(sumas)-1):
  if max<sumas[t+1]:
    max=sumas[t+1]
    pos=t+1
print('la linea mas afluente es la', str(lin[pos]))

plt.plot(sumas,lin,color='orange', marker='o', linestyle='dashed',
     linewidth=2, markersize=12)
plt.show()

'''linea menos afluente'''
import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      lineas_m.append(renglon[3])
      afluencia.append(renglon[5])
      lineas += 1
lin=[]
for i in range (len(lineas_m)):
  if lineas_m[i] not in lin:
    lin.append(lineas_m[i])
sumas=[]
for j in range(len(lin)):
  suma=0
  for k in range(len(lineas_m)):
    if lineas_m[k] == lin[j]:
      suma=suma+int(afluencia[k])
  sumas.append(suma)
min= sumas[0]
pos= 1
for t in range(len(sumas)-1):
  if min>sumas[t+1]:
    min=sumas[t+1]
    pos=t+1
print('la linea menos afluente es la', str(lin[pos]))

'''año mas afluente vs año menos afluente'''

import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      años.append(renglon[1])
      afluencia.append(renglon[5])
      lineas += 1
an=[]
for i in range (len(años)):
  if años[i] not in an:
    an.append(años[i])
sumas=[]
for j in range(len(an)):
  suma=0
  for k in range(len(años)):
    if años[k] == an[j]:
      suma=suma+int(afluencia[k])
  sumas.append(suma)
max= sumas[0]
pos= 1
for t in range(len(sumas)-1):
  if max<sumas[t+1]:
    max=sumas[t+1]
    pos=t+1
min = sumas[0]
pos_m = 1
for f in range(len(sumas)-1):
  if min>sumas[t+1]:
    min=sumas[t+1]
    pos_m=t+1
dif=sumas[pos]-sumas[pos_m]
print(str(an[pos_m-1]))
print('el año mas afluente es:', str(an[pos]), 'con', str(sumas[pos]), 'usuarios')
print('el año menos afluente es:', str(an[pos_m]), 'con', str(sumas[pos_m]), 'usuarios')
print('La diferencia de usuarios entre el año mas y menos afluente es de', str(dif), 'usuarios')
import matplotlib.pyplot as plt

plt.plot(sumas,an,color='orange', marker='o', linestyle='dashed',
     linewidth=2, markersize=12)

'''Crecimiento de las lineas en afluencia'''
import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      lineas_m.append(renglon[3]) #se crean dos listas con los datos de afluencias y las lineas
      afluencia.append(renglon[5])
      años.append(renglon[1])
      lineas += 1
lin=[]

for i in range (len(lineas_m)):
  if lineas_m[i] not in lin:
    lin.append(lineas_m[i])
sumas_2010=[]
sumas_2023=[]
for j in range(len(lin)):
  suma_2010=0
  suma_2023=0
  for k in range(len(lineas_m)):
    if lineas_m[k] == lin[j] and int(años[k])==2010:
      suma_2010=suma_2010+int(afluencia[k])
  sumas_2010.append(suma_2010)
  for k in range(len(lineas_m)):
    if lineas_m[k] ==lin[j] and int(años[k])==2023:
      suma_2023=suma_2023+int(afluencia[k])
  sumas_2023.append(suma_2023)
diferencias=[]
for f in range(len(sumas_2010)):
  dif=(sumas_2010[f]-sumas_2023[f])
  diferencias.append(dif)

suma=0
for n in range(len(diferencias)):
  suma=suma+diferencias[n]
promedio=suma/len(diferencias)
for s in range(len(diferencias)):
  if promedio<diferencias[s]:
    print('La',str(lin[s]),'tuvo un crecimiento en su afluencia mayor al promedio')

import matplotlib.pyplot as plt
plt.plot(lin,diferencias,color='orange', marker='o', linestyle='dashed',
     linewidth=2, markersize=12)

'''razón entre los usuarios del primer y ultimo año'''

import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      años.append(renglon[1])
      afluencia.append(renglon[5])
      lineas += 1
an=[]
for i in range (len(años)):
  if años[i] not in an:
    an.append(años[i])
sumas=[]
for j in range(len(an)):
  suma=0
  for k in range(len(años)):
    if años[k] == an[j]:
      suma=suma+int(afluencia[k])
  sumas.append(suma)
#vamos a sacar dos razones ya que el año 2023 está inconcluso en la base de datos
razon1= int(sumas[-1])/int(sumas[0])
print('La razón de los usuarios que viajaron en el 2010 contra el 2023 es de',str(razon1))
razon2= int(sumas[-2])/int(sumas[0])
print('La razón de los usuarios que viajaron en el 2010 contra el 2023 es de',str(razon2))

'''estacion mas afluente de la linea mas afluente'''

import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      lineas_m.append(renglon[3])
      afluencia.append(renglon[5])
      estaciones.append(renglon[4])
      lineas += 1
est=[]
x='Linea 2'
for i in range (len(estaciones)):
  if estaciones[i] not in est and lineas_m[i] == x:
    est.append(estaciones[i])
sumas=[]
for j in range(len(est)):
  suma=0
  for k in range(len(estaciones)):
    if estaciones[k] == est[j]:
      suma=suma+int(afluencia[k])
  sumas.append(suma)
max= sumas[0]
pos= 1
for t in range(len(sumas)-1):
  if max<sumas[t+1]:
    max=sumas[t+1]
    pos=t+1
print('la estación mas afluente de la linea mas afluente es', str(est[pos]))

import matplotlib.pyplot as plt
plt.plot(sumas,est,color='orange', marker='o', linestyle='dashed',linewidth=2, markersize=10)

'''estacion menos afluente de la linea mas afluente'''

import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      lineas_m.append(renglon[3])
      afluencia.append(renglon[5])
      estaciones.append(renglon[4])
      lineas += 1
est=[]
x='Linea 2'
for i in range (len(estaciones)):
  if estaciones[i] not in est and lineas_m[i] == x:
    est.append(estaciones[i])
sumas=[]
for j in range(len(est)):
  suma=0
  for k in range(len(estaciones)):
    if estaciones[k] == est[j] :
      suma=suma+int(afluencia[k])
  sumas.append(suma)
min= sumas[0]
pos= 1
for t in range(len(sumas)-1):
  if min>sumas[t+1]:
    min=sumas[t+1]
    pos=t+1
print('la estación menos afluente de la linea mas afluente es ', str(est[pos]))

# afluencia de los meses 2010-2016
import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      fechas.append(renglon[0])
      años.append(renglon[1])
      meses.append(renglon[2])
      lineas_m.append(renglon[3])
      estaciones.append(renglon[4])
      afluencia.append(renglon[5])
      lineas += 1

mes = []
for i in range(len(meses)):
  if meses[i] not in mes:
    mes.append(meses[i])

mespro = []
for j in range(len(mes)):
  suma = 0
  dias = 0
  for k in range(len(meses)):
    if meses[k] == mes[j] and int(años[k]) <= 2016:
      suma = suma + int(afluencia[k])
      dias += 1
  pro = suma // dias
  mespro.append(pro)

max = mespro[0]
pos = 1
for t in range(len(mespro)-1):
	if max < mespro[t+1]:
		max = mespro[t+1]
		pos = t + 1

print('El mes con más afluencia en en periodo 2010-2016 es: ' + str(mes[pos]) + ' con un promedio de ' + str(max))

matplotlib

# afluencia de los meses 2017-2023
import csv
fechas = [] #renglon 0
años = [] #renglon 1
meses = [] #renglon 2
lineas_m = [] #renglon 3
estaciones = [] #renglon 4
afluencia = [] #renglon 5
ind = 0
with open('/content/drive/My Drive/afluenciastc_simple_07_2023.csv',mode = 'r' , encoding = 'utf-8') as csvfile:
  csv_leido = csv.reader(csvfile,delimiter=',')
  lineas = 0
  for renglon in csv_leido:
    if lineas == 0:
      lineas =+1
    else:
      fechas.append(renglon[0])
      años.append(renglon[1])
      meses.append(renglon[2])
      lineas_m.append(renglon[3])
      estaciones.append(renglon[4])
      afluencia.append(renglon[5])
      lineas += 1

mes = []
for i in range(len(meses)):
  if meses[i] not in mes:
    mes.append(meses[i])

mespro = []
for j in range(len(mes)):
  suma = 0
  dias = 0
  for k in range(len(meses)):
    if meses[k] == mes[j] and int(años[k]) >= 2017:
      suma = suma + int(afluencia[k])
      dias += 1
  pro = suma // dias
  mespro.append(pro)

max = mespro[0]
pos = 1
for t in range(len(mespro)-1):
	if max < mespro[t+1]:
		max = mespro[t+1]
		pos = t + 1

print('El mes con más afluencia en en periodo 2017-2023 es: ' + str(mes[pos]) + ' con un promedio de ' + str(max))

x=1000*(10**(50))+1
print(x)